version: "0.2"
volumes:
  mysql_vol_test:
services:
  jupyter:
    container_name: gpu-jupyter
    hostname: jupyterlab
    # restart: always
    build: ./docker/gpu
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    ports:
      - "8400:8888"
    environment:
      - JUPYTER_TOKEN=${jupyter_pw}
    env_file:
      - jupyter.env
    volumes:
      - .:/app